[general]
import = ["~/.config/alacritty/theme.toml"]
live_config_reload = true


[debug]
renderer = "Glsl3"


[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"


[window]
opacity = 1.0

[window.padding]
x = 12
y = 12
