import = ["~/.config/alacritty/theme.toml"]

live_config_reload = true
window.opacity = 1.0


[debug]
renderer = "gles2_pure"

[shell]
program = "/bin/zsh"


[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"


[window.padding]
x = 12
y = 12
